# Generated by Django 5.2.3 on 2025-06-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_link_alter_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='contant',
            new_name='content',
        ),
    ]
